name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read
 
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Authenticate to Google Cloud
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: "//iam.googleapis.com/projects/287702920783/locations/global/workloadIdentityPools/tf-pool/compute.googleapis.com"
        service_account: "tf-pool@advance-terraform-406410.iam.gserviceaccount.com"
        # Assume the audience is the same as the provider ID for simplicity, double-check your specific requirements
        audience: "//iam.googleapis.com/projects/287702920783/locations/global/workloadIdentityPools/tf-pool/compute.googleapis.com"

    - name: Terraform Init
      run: terraform init
      working-directory: ./001

    - name: Terraform Plan
      run: TF_LOG=DEBUG terraform plan -out=tfplan
      working-directory: ./001

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./001
      if: github.ref == 'refs/heads/main'
